resources:
  - name: bld_npm_backend
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: Github_maharshi
      # Repository path, including org name/repo name
      path: maharshipatel/nodejs-sample-project
      branches:
        # Specifies which branches will trigger dependent steps
        include: main

  - name: NpmBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art

pipelines:
  - name: npm_pipeline_jfp_example
    steps:
      - name: npm_build_step
        type: NpmBuild
        configuration:
          repositoryName: npm-virtual      # required, npm repository name on artifacctory
          sourceLocation: .      # required, location of package.json file
          integrations:
            - name:  art  # required
          inputResources:
            - name: bld_npm_backend         # required

      - name: npm_publish_step
        type: NpmPublish
        configuration:
          # for payloadType npm:
          repositoryName: npm-virtual        # required, npm repository name on artifactory
          autoPublishBuildInfo: false       # optional
          integrations:
            - name: art      # required
          inputSteps:
            - name: npm_build_step                # required