resources:
- name: MaharshiPatel_nodeJs_sample_project_gitResource
  type: GitRepo
  configuration:
    path: MaharshiPatel/nodeJs-sample-project
    gitProvider: github_MaharshiPatel_nodeJs_sample_project_integration
    buildOn:
      pullRequestCreate: true
    branches:
      include: main
- name: MaharshiPatel_nodeJs_sample_project_buildInfoResource
  type: BuildInfo
  configuration:
    sourceArtifactory: rt_MaharshiPatel_nodeJs_sample_project_integration
    buildName: nodeJs-sample-project-main
    buildNumber: $run_number
pipelines:
- name: MaharshiPatel_nodeJs_sample_project_pipeline
  configuration:
    environmentVariables:
      readOnly:
        CI: "true"
        JFROG_CLI_BUILD_NAME: nodeJs-sample-project-main
        JFROG_CLI_BUILD_NUMBER: $run_number
        JFROG_CLI_BUILD_URL: $step_url
  steps:
  - name: NpmBuildStep
    type: Bash
    configuration:
      environmentVariables:
        JFROG_BUILD_STATUS: PASS
      integrations:
      - name: rt_MaharshiPatel_nodeJs_sample_project_integration
      inputResources:
      - name: MaharshiPatel_nodeJs_sample_project_gitResource
    execution:
      onExecute:
      - cd $res_MaharshiPatel_nodeJs_sample_project_gitResource_resourcePath
      - jfrog rt c MaharshiPatel_nodeJs_sample_project_serverId --url $int_rt_MaharshiPatel_nodeJs_sample_project_integration_url
        --user $int_rt_MaharshiPatel_nodeJs_sample_project_integration_user --enc-password=false
      - jfrog rt npm-config --server-id-resolve MaharshiPatel_nodeJs_sample_project_serverId
        --repo-resolve sup016-npm-virtual
      - jfrog rt npmi
      - jfrog rt bag
      - jfrog rt bce
      onComplete:
      - add_run_files /tmp/jfrog/. jfrog
      onFailure:
      - export JFROG_BUILD_STATUS=FAIL
      - jfrog rt bce
      - jfrog rt bp
  - name: PublishBuildInfoStep
    type: PublishBuildInfo
    configuration:
      inputResources:
      - name: MaharshiPatel_nodeJs_sample_project_gitResource
      outputResources:
      - name: MaharshiPatel_nodeJs_sample_project_buildInfoResource
      inputSteps:
      - name: NpmBuildStep
      forceXrayScan: true
    execution:
      onComplete:
      - update_commit_status MaharshiPatel_nodeJs_sample_project_gitResource
